"""status id

Revision ID: 1071665e8274
Revises: 344b7147624a
Create Date: 2025-05-29 13:43:47.520114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1071665e8274'
down_revision: Union[str, None] = '344b7147624a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validations', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_column('validations', 'is_valid')
    op.drop_column('validations', 'validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validations', sa.Column('validated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('validations', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('validations', 'status_id')
    # ### end Alembic commands ###
