version: '3.9'

services:
  backend:
    image: ghcr.io/bani2016up/sae-backend:latest
    restart: on-failure
    working_dir: /app/src
    ports:
      - "8080:8080"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./backend:/app
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    entrypoint:
      - /bin/sh
      - -c
      - |
        PGUSER=$$(cat /run/secrets/postgres_user)
        PGPASSWORD=$$(cat /run/secrets/postgres_password)
        PGDATABASE=$$(cat /run/secrets/postgres_db)

        export SQLALCHEMY_DATABASE_URL="postgresql+asyncpg://$$PGUSER:$$PGPASSWORD@db:5432/$$PGDATABASE"
        export DATABASE_URL="$$SQLALCHEMY_DATABASE_URL"

        poetry run alembic upgrade head
        poetry run python -m spacy download en_core_web_trf
        exec poetry run python main.py

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    ports:
      - "5432:5432"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

secrets:
  postgres_user:
    file: ./secrets/postgres/postgres_user
  postgres_password:
    file: ./secrets/postgres/postgres_password
  postgres_db:
    file: ./secrets/postgres/postgres_db

volumes:
  postgres_data:
