version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sae-backend:latest
    ports:
      - "8080:6969"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sae_db
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./:/app
    command: poetry run python src/main.py

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sae_db
      - POSTGRES_HOST=4001
    ports:
      - "4001:4001"

volumes:
  postgres_data:
