"""error models upgreaded

Revision ID: cc1a45386328
Revises: 89b06bdd11fd
Create Date: 2025-04-27 03:35:55.692370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1a45386328'
down_revision: Union[str, None] = '89b06bdd11fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'validations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validations', type_='foreignkey')
    op.drop_column('validations', 'user_id')
    # ### end Alembic commands ###
