name: Deploy SAE


on:
  push:
    branches:
      - compose-fix
  release:
    types: [published]

env:
  BRANCH: compose-fix

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize owner name
        run: echo "OWNER_LC=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: backend/
          file: backend/Dockerfile
          tags: ghcr.io/${{ env.OWNER_LC }}/sae-backend:latest
          push: true
          platforms: linux/amd64
  

  deploy:
    name: Deploy via docker-compose.deploy.yml
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ./sae
            git checkout ${{ env.BRANCH }}
            git pull 
            docker-compose -f docker-compose.deploy.yml pull backend
            docker-compose -f docker-compose.deploy.yml up -d --no-recreate backend
